<?php


//require_once '../conf/config.php';

class DB extends MysqliDb
{
    public function __construct($host = null, $username = null, $password = null, $db = null, $port = null, $charset = 'utf8', $socket = null)
    {
        parent::__construct($host, $username, $password, $db, $port, $charset, $socket);

    }

    public function get($tableName, $numRows = null, $columns = '*')
    {
        return parent::get($tableName, $numRows, $columns); // TODO: Change the autogenerated stub
    }


    public function column($conn, $table, $id, $col)
    {

        $items = $conn->get($table, 200, $col);
        foreach ($items as $item => $arr) {
            //echo $item . '<br>';
            foreach ($arr as $key => $val) {
                if ($item === $id+1) {
                    //echo $key . '<br>';
                    //echo $val . '<br>';
                    $column = $val;
                    return $column;
                }
            }
        }

    }

    public function updateWhere( $field, $arr)
    {
        for ($n = 0; $n < 2; $n++){

            $table = DB_TAB;
            $data= array($field => $arr[0],
            );
        }
        $update = $this->update($table, $data, '1');
        return $update;
    }


}










